# មេកានិចការយកចិត្តទុកដាក់ និង ម៉ាស៊ីនបម្លែង

ខ្សែបណ្តោទមួយចំណុចសំខាន់នៃបណ្តាញប្រើប្រាស់ស្តើងគឺថាពាក្យទាំងអស់ក្នុងតួអក្សរមានឥទ្ធិពលដូចគ្នានៅលើលទ្ធផល។ វាបង្កឲ្យមានការទទួលបានកម្មវិធីមិនល្អជាមួយម៉ូដែលកម្មវិធីស្តើង LSTM គំរូលើបំណងពីតួអក្សរទៅតួអក្សរ ដូចជា ការទទួលស្គាល់អត្តសញ្ញាណឈ្មោះ និង ការបកប្រែម៉ាស៊ីន។ នៅក្នុងការពិត ពាក្យជាក់លាក់ក្នុងជួរមូលដ្ឋានបញ្ចូលជាញឹកញាប់មានឥទ្ធិពលលើលទ្ធផលរំដោះជាមុនជាងពាក្យផ្សេងទៀត។

សូមគិតពីម៉ូដែលជួរមូលដ្ឋានពីតួអក្សរទៅតួអក្សរ ដូចជាការបកប្រែម៉ាស៊ីន។ វាត្រូវបានអនុវត្តដោយបណ្តាញប្រើប្រាស់ស្តើងពីរមួួយដែលបណ្តាញមួយ (**encoder**) នឹងបង្រួមជួរមូលដ្ឋានបញ្ចូលទៅជាអថេរភាពលាក់ ហើយមួយទៀត **decoder** នឹងបំបែកចេញពីអថេរភាពលាក់នេះទៅជាលទ្ធផលបកប្រែ។ បញ្ហានៃវិធីសាស្រ្តនេះគឺអថេរភាពចុងក្រោយនៃបណ្តាញនឹងមានការលំបាកក្នុងការចងចាំការចាប់ផ្តើមនៃប្រយោគ ដូច្នេះបង្កឲ្យគុណភាពអ្នកម៉ូដែលនៅលើប្រយោគវែងក្រាប។

**មេកានិចការយកចិត្តទុកដាក់** ផ្ដល់នូវវិធីសាស្រ្តក្នុងការផ្ដល់ទម្ងន់ទៅលើឥទ្ធិពលបរិបទនៃវ៉ិចទ័របញ្ចូលនីមួយៗលើការព្យាករណ៍លទ្ធផលនីមួយៗនៃ RNN។ វិធីសាស្រ្តកំណត់នេះគឺដោយបង្កើតផ្លូវរហ័សរវាងស្ថានភាពចន្លោះនៃ RNN បញ្ចូល និង RNN លទ្ធផល។ ដោយរបៀបនេះ នៅពេលបង្កើតសញ្ញាលទ្ធផល $y_t$ យើងនឹងគិតថាជាមួយនឹងស្ថានភាពលាក់បញ្ចូលទាំង អាច $h_i$ ដែលមានទម្ងន់ខុសគ្នា $\alpha_{t,i}$ ។

![រូបភាពបង្ហាញម៉ូដែល encoder/decoder ជាមួយស្រទាប់ការយកចិត្តទុកដាក់បន្ថែម](../../../../../translated_images/km/encoder-decoder-attention.7a726296894fb567.webp)
*ម៉ូដែល encoder-decoder ជាមួយមេកានិចការយកចិត្តទុកដាក់បន្ថែម ក្នុង [Bahdanau et al., 2015](https://arxiv.org/pdf/1409.0473.pdf), បានយោងពី [អត្ថបទប្លុកនេះ](https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html)*

ម៉ាទិកខ្យល់ការយកចិត្តទុកដាក់ $\{\alpha_{i,j}\}$ នឹងតំណាងឱ្យកម្រិតដែលពាក្យបញ្ចូលជាក់លាក់មានតួនាទីក្នុងការបង្កើតពាក្យចេញមួយនៅក្នុងជួរលទ្ធផល។ ខាងក្រោមនេះគឺជាឧទាហរណ៍នៃម៉ាទិកខ្យល់បែបនេះ៖

![រូបភាពបង្ហាញការចំរូងគំរូដែលបានរកឃើញដោយ RNNsearch-50 យកមកពី Bahdanau - arviz.org](../../../../../translated_images/km/bahdanau-fig3.09ba2d37f202a6af.webp)

*រូបថតយកពី [Bahdanau et al., 2015](https://arxiv.org/pdf/1409.0473.pdf) (រូប3)*

មេកានិចការយកចិត្តទុកដាក់មានការទទួលខុសត្រូវចម្បងចំពោះស្ថានភាពបច្ចុប្បន្ន ឬ ហៀបឆាប់នៃការបំពេញភាសាធម្មជាតិ។ ការបន្ថែមការយកចិត្តទុកដាក់ប៉ុន្មានតំឡើងចំនួនប្រ៉ាម៉ែត្រ ម៉ូដែលទៅលើបញ្ហាប្រឈមក្នុងការតម្រាស់ជាមួយ RNNs។ ការរឹតបន្តឹងសំខាន់នៃការតម្រាស់ RNN គឺថារូបភាពបណ្តាញលំដាប់ហាក់ដូចជាការលំបាកក្នុងការធ្វើបាត់ជាស្វ័យប្រវត្តិ និង ធ្វើបាត់ពេញលេញ។ ក្នុង RNN, ធាតុនីមួយនៃជួរត្រូវបានដំណើរការប្រមូលក្នុងលំដាប់ក្រោមលំដាប់ ដែលមានន័យថាវាមិនអាចធ្វើបានពេញលេញលើបណ្តាត។

ការទទួលយកមេកានិចការយកចិត្តទុកដាក់រួមជាមួយនឹងការរឹតបន្តឹងនេះបង្កើតឡើងវិធីម៉ូដែលម៉ាស៊ីនបម្លែងដែលពេញនិយមឥឡូវនេះដែលយើងស្គាល់និងប្រើប្រាស់ពី BERT ដល់ OpenGPT3។

## ម៉ូដែលម៉ាស៊ីនបម្លែង

ជំនួសការដាក់បញ្ជូនបរិបទនៃការព្យាករណ៍មុនទៅជាដំណាក់កាលវាយតម្លៃបន្ទាប់, **ម៉ូដែលម៉ាស៊ីនបម្លែង** ប្រើប្រាស់ **កូដទីតាំង** និង **ការយកចិត្តទុកដាក់** ដើម្បីទទួលយកបរិបទនៃបញ្ចូលមួយនៅក្នុងផ្ទៃវិនទស្សន៍អត្ថបទដែលបានផ្ដល់។ រូបភាពខាងក្រោមបង្ហាញពីរបៀបដែលកូដទីតាំងជាមួយការយកចិត្តទុកដាក់អាចទទួលយកបរិបទនៅក្នុងផ្ទៃវិនទស្សន៍មួយបាន។

![រូបភាព GIF រូបចលនា បង្ហាញពីរបៀបចាត់ធ្វើវាយតម្លៃនៅក្នុងម៉ូដែលម៉ាស៊ីនបម្លែង។](../../../../../lessons/5-NLP/18-Transformers/images/transformer-animated-explanation.gif) 

ដោយសារតែទីតាំងបញ្ចូលនីមួយៗត្រូវបានផ្គូផ្គងដោយខ្លួនឯងទៅទីតាំងលទ្ធផលនីមួយៗ ម៉ូដែលម៉ាស៊ីនបម្លែងអាចធ្វើបាត់បានល្អជាង RNNs ដែលអនុញ្ញាតឲ្យមានម៉ូដែលភាសាធាតុធំជាងនិងបង្ហាញវឌ្ឍនភាពល្អជាង។ ក្បាលការយកចិត្តទុកដាក់នីមួយៗអាចប្រើក្នុងការរៀនទំនាក់ទំនងផ្សេងៗរវាងពាក្យដែលបង្កើនការងារជាបន្ទាប់នៃការបំលាស់ភាសាធម្មជាតិ។

## ការបង្កើតម៉ូដែលម៉ាស៊ីនបម្លែងសាមញ្ញ

Keras មិនមានស្រទាប់ម៉ាស៊ីនបម្លែងបញ្ចូលទេ ប៉ុន្តែយើងអាចបង្កើតរបស់យើងផ្ទាល់បាន។ ដូចមុន យើងនឹងផ្ដោតលើការចាត់ថ្នាក់អត្ថបទនៃទិន្នន័យព័ត៌មាន AG News ប៉ុន្តែគួររំលឹកថា ម៉ូដែលម៉ាស៊ីនបម្លែងបង្ហាញលទ្ធផលល្អបំផុតនៅលើបញ្ហា NLP ដែលពិបាកជាង។


In [1]:
import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds
import numpy as np

ds_train, ds_test = tfds.load('ag_news_subset').values()

def extract_text(x):
    return x['title']+' '+x['description']

def tupelize(x):
    return (extract_text(x),x['label'])

ស្រទាប់ថ្មីៗនៅក្នុង Keras គួរត្រូវបានបង្កើតជាកូនថ្នាក់ subclass របស់ថ្នាក់ `Layer` ហើយអនុវត្តវិធីសាស្រ្ត `call`។ យើងចាប់ផ្តើមជាមួយស្រទាប់ **Positional Embedding** ។ យើងនឹងប្រើ [កូដមួយចំនួនពីឯកសារផ្លូវការរបស់ Keras](https://keras.io/examples/nlp/text_classification_with_transformer/)។ យើងនឹងនិយមថាយើងដាក់សម្អាតចំនួនទាំងអស់នៃលំដាប់បញ្ចូលអោយមានប្រវែង `maxlen`។


In [2]:
class TokenAndPositionEmbedding(keras.layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.token_emb = keras.layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = keras.layers.Embedding(input_dim=maxlen, output_dim=embed_dim)
        self.maxlen = maxlen

    def call(self, x):
        maxlen = self.maxlen
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x+positions

ស្រទាប់នេះមានស្រទាប់ `Embedding` ពីរ៖ សម្រាប់ជំរៅសញ្ញាណ (ទៅតាមវិធីដែលយើងបានពិភាក្សាកាន់មុន) និងមុខតំណែងសញ្ញាណ។ មុខតំណែងសញ្ញាណត្រូវបានបង្កើតជាខ្សែដដែលនៃលេខធម្មជាតិចាប់ពី 0 រហូតដល់ `maxlen` ដោយប្រើ `tf.range` ហើយបន្ទាប់មកផ្ញើតាមស្រទាប់ embedding។ វិចទ័រជួរ embedding ពីរដែលទទួលបានបន្ថែមគ្នា ដើរការផលិតតំណាងមុខតំណែងដែលជាស្អាតបញ្ចូលដែលមានទ្រង់ទ្រាយជា `maxlen`$\times$`embed_dim`។

<img src="../../../../../translated_images/km/pos-embedding.e41ce9b6cf6078af.webp" width="40%"/>

ឥឡូវនេះ, សូមអនុវត្តប្លុក transformer។ វានឹងទទួលផលបញ្ចេញពីស្រទាប់ embedding ដែលបានកំណត់ពីមុន៖


In [3]:
class TransformerBlock(keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim, name='attn')
        self.ffn = keras.Sequential(
            [keras.layers.Dense(ff_dim, activation="relu"), keras.layers.Dense(embed_dim),]
        )
        self.layernorm1 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = keras.layers.Dropout(rate)
        self.dropout2 = keras.layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

Transformer ប្រើ `MultiHeadAttention` លើអិនប៊ុតដែលត្រូវបានកូដតាមទីតាំង ដើម្បីបង្កើតវ៉ិចទ័រយល់ដឹងមានវិមាត្រ `maxlen`$\times$`embed_dim`, ដែលបន្ទាប់មកត្រូវបានច្របាច់ជាមួយអិនប៊ុត ហើយធ្វើការប្រកួតប្រជែងដោយប្រើ `LayerNormalizaton`។

> **សំគាល់**: `LayerNormalization` ស្រដៀងទៅនឹង `BatchNormalization` ដែលបានពិភាក្សា​នៅក្នុងផ្នែក *Computer Vision* នៃផ្លូវការសិក្សានេះ ប៉ុន្តែវាធ្វើការប្រកួតប្រជែងលទ្ធផលនៃស្រទាប់មុន សម្រាប់គំរូសិក្សាទាំងមូលដោយឯករាជ្យ ដើម្បីនាំឲ្យវាផ្លាស់ទៅក្នុងជួរទីតាំង [-1..1]។

លទ្ធផលនៃស្រទាប់នេះបន្ទាប់មកត្រូវបានផ្ញើតាមរយៈបណ្ដាញ `Dense` (សម្រាប់ករណីរបស់យើង - ប៉ឺរប្រើតូនពីរស្រទាប់), ហើយលទ្ធផលត្រូវបានបន្ថែមទៅលើលទ្ធផលចុងក្រោយ (ដែលត្រូវបានធ្វើប្រកួតប្រជែងម្តងទៀត)។

<img src="../../../../../translated_images/km/transformer-layer.905e14747ca4e7d5.webp" width="30%" />

ឥឡូវនេះ, យើងត្រៀមខ្លួនសម្រាប់កំណត់ម៉ូដែល transformer ពេញលេញ៖


In [4]:
embed_dim = 32  # Embedding size for each token
num_heads = 2  # Number of attention heads
ff_dim = 32  # Hidden layer size in feed forward network inside transformer
maxlen = 256
vocab_size = 20000

model = keras.models.Sequential([
    keras.layers.experimental.preprocessing.TextVectorization(max_tokens=vocab_size,output_sequence_length=maxlen, input_shape=(1,)),
    TokenAndPositionEmbedding(maxlen, vocab_size, embed_dim),
    TransformerBlock(embed_dim, num_heads, ff_dim),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(20, activation="relu"),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(4, activation="softmax")
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
text_vectorization (TextVect (None, 256)               0         
_________________________________________________________________
token_and_position_embedding (None, 256, 32)           648192    
_________________________________________________________________
transformer_block (Transform (None, 256, 32)           10656     
_________________________________________________________________
global_average_pooling1d (Gl (None, 32)                0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 20)                660       
_________________________________________________________________
dropout_3 (Dropout)          (None, 20)               

In [5]:
print('Training tokenizer')
model.layers[0].adapt(ds_train.map(extract_text))
model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer='adam')
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

Training tokenizer
938/938 [==============================] - 45s 39ms/step - loss: 0.4978 - acc: 0.8068 - val_loss: 0.2808 - val_acc: 0.9124


## គំរូប្រព័ន្ធបំលែង BERT

**BERT** (Bidirectional Encoder Representations from Transformers) គឺជាបណ្តុំបំលែងស្រទាប់ច្រើនអព្ភូតមាន ១២ ស្រទាប់សម្រាប់ *BERT-base* និង ២៤ ស្រទាប់សម្រាប់ *BERT-large*។ គំរូនេះត្រូវបានបណ្តុះជាមុនលើសំណុំអត្ថបទធំនៅ (WikiPedia + សៀវភៅ) ដោយប្រើការបណ្តុះដោយគ្មានមគ្គុទេសក៍ (ប៉ាន់ណាចាត់ពាក្យដែលបានលាក់នៅក្នុងប្រយោគ)។ ក្នុងអំឡុងពេលបណ្តុះជាមុន គំរូនេះចំណូលទៅក្នុងការយល់ដឹងភាសាដោយមានកម្រិតខ្ពស់ ដែលបន្ទាប់មកអាចប្រើប្រាស់ជាមួយសំណុំទិន្នន័យផ្សេងទៀតដោយប្រើការតំរូវតែម្ដង។ ដំណើរការនេះហៅថា **transfer learning**។ 

![រូបភាពពី http://jalammar.github.io/illustrated-bert/](../../../../../translated_images/km/jalammarBERT-language-modeling-masked-lm.34f113ea5fec4362.webp)

មានរចនាសម្ព័ន្ធបំលែងជាច្រើន រួមមាន BERT, DistilBERT, BigBird, OpenGPT3 និងផ្សេងទៀតដែលអាចត្រូវបានតំរូវតែម្ដងបាន។ 

យើងទៅប្រើគំរូ BERT ដែលបានបណ្តុះជាមុនសម្រាប់ដោះស្រាយបញ្ហាការបែងចែកលំដាប់ធម្មតារបស់យើង។ យើងនឹងខ្ចីគំនិត និងកូដខ្លះពី [ឯកសារផ្លូវការជាផ្លូវការ](https://www.tensorflow.org/text/tutorials/classify_text_with_bert)។

ដើម្បីបញ្ចូលគំរូដែលបានបណ្តុះជាមុន យើងនឹងប្រើ **Tensorflow hub**។ ជំហានដំបូង សូមបញ្ចូលវ៉ិចទ័រពិសេសសម្រាប់ BERT៖


In [1]:
import tensorflow_text 
import tensorflow_hub as hub
vectorizer = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3')

ModuleNotFoundError: No module named 'tensorflow_text'

In [7]:
vectorizer(['I love transformers'])

{'input_type_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_word_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
 array([[  101,  1045,  2293, 19081,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0, 

វាសំខាន់ណាស់ដែលអ្នកប្រើនូវកាតាក្រហមដូចគ្នានឹងដែលបណ្តាញដើមបានបណ្តុះបណ្តាលលើវា។ ផងដែរឧបករណ៍បម្លែង BERT ត្រឡប់មកវិញនូវធាតុបី:
* `input_word_ids` ដែលជាដំណើរការប្រភេទលេខកូដសម្រាប់វាក្យបញ្ជូល
* `input_mask` បង្ហាញថាផ្នែកណានៃលំដាប់មានបញ្ចូលពិតប្រាកដ និងផ្នែកណាគឺជាការបន្លំ។ វាស្រដៀងនឹងម៉ាសដែលបានផលិតពីស្រទាប់ `Masking`
* `input_type_ids` ត្រូវបានប្រើសម្រាប់បេសកកម្មគំរូភាសា ហើយអនុញ្ញាតឱ្យបញ្ជាក់ពីប្រយោគបញ្ចូលពីរនៅលើលំដាប់មួយ។

បន្ទាប់មក យើងអាចបង្កើតប្រភពយកលក្ខណៈពិសេស BERT បាន៖


In [8]:
bert = hub.KerasLayer('https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-128_A-2/1')

In [9]:
z = bert(vectorizer(['I love transformers']))
for i,x in z.items():
    print(f"{i} -> { len(x) if isinstance(x, list) else x.shape }")

pooled_output -> (1, 128)
encoder_outputs -> 4
sequence_output -> (1, 128, 128)
default -> (1, 128)


ដូច្នេះស្រទាប់ BERT នាំមកនូវលទ្ធផលប្រយោជន៍ជាច្រើន៖
* `pooled_output` គឺជាលទ្ធផលនៃការពន្លឿនច<Token>ងទាំងអស់ក្នុងលំដាប់។ អ្នកអាច xem វាជាបទបញ្ញាសម្ខេបស្មារតីនៃបណ្តាញទាំងមូល។ វាស្មើនឹងលទ្ធផលនៃស្រទាប់ `GlobalAveragePooling1D` ក្នុងគំរូមុនរបស់យើង។
* `sequence_output` គឺជាលទ្ធផលនៃស្រទាប់បម្លែងចុងក្រោយ (សមស្របនឹងលទ្ធផលនៃ `TransformerBlock` នៅក្នុងគំរូរបស់យើងខាងលើ)
* `encoder_outputs` គឺជាលទ្ធផលនៃស្រទាប់បម្លែងទាំងអស់។ ដោយសារយើងបានផ្ទុកគំរូ BERT ៤ ស្រទាប់ (ដូចដែលអ្នកអាចសន្មត់ពីឈ្មោះដែលមាន `4_H` នៅក្នុង), វាមានតង់ស័រចំនួន ៤។ តង់ស័រចុងក្រោយមានដូចគ្នានឹង `sequence_output`។

ឥឡូវនេះយើងនឹងកំណត់គំរូចំណាត់ថ្នាក់ពីដើមដល់បញ្ចប់។ យើងនឹងប្រើ *ការ​កំណត់​គំរូ​តាម​អនុគមន៍* កាលណា​យើង​កំណត់​អ៊ី​ន​ពុ­t​ជុំវិញ​គំរូ ហើយបន្ទាប់មកផ្ដល់សរសេរ​អត្ថបទជាសំណុំពីរៀបរាប់របៀបគណនា​លទ្ធផល​របស់វា។ យើងនឹងក៏ធ្វើឲ្យទម្ងន់គំរូ BERT មិនអាចបណ្តុះបណ្តាលបាន សិងបណ្តុះបណ្តាលគ្រាន់តែ​អ្នកចំណាត់ថ្នាក់ចុងបញ្ចប់តែប៉ុណ្ណោះៈ


In [10]:
inp = keras.Input(shape=(),dtype=tf.string)
x = vectorizer(inp)
x = bert(x)
x = keras.layers.Dropout(0.1)(x['pooled_output'])
out = keras.layers.Dense(4,activation='softmax')(x)
model = keras.models.Model(inp,out)
bert.trainable = False
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           input_1[0][0]                    
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 4782465     keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

In [11]:
model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer='adam')
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

938/938 [==============================] - 528s 559ms/step - loss: 0.8056 - acc: 0.6983 - val_loss: 0.5953 - val_acc: 0.7888


ទោះបីជាម៉ោងប៉ារ៉ាម៉ែត្រដែលអាចបណ្តុះបណ្តាលបានមានតិចក៏ដោយ ប៉ុន្តែដំណើរការនេះយឺតណាស់ ដោយសារតែអ្នកដកស្រង់លក្ខណៈ BERT មានគណនាពិបាក។ វាដូចជាយើងមិនអាចទទួលបានភាពត្រឹមត្រូវសមរម្យទេ ម្ដងទេដោយសារ ការខ្វះការបណ្តុះបណ្តាល ឬការខ្វះម៉ូដែលប៉ារ៉ាម៉ែត្រ។

ឲ្យព្យាយាមបញ្ចេញទម្ងន់ BERT ហើយបណ្តុះបណ្តាលវាផងដែរ។ នេះទាមទារពីអត្រាការសិក្សាខ្លាំងតិច និងយុទ្ធសាស្ត្របណ្តុះបណ្តាលប្រុងប្រយ័ត្នជាមួយ **warmup** ដោយប្រើ **AdamW** អុបទីម៉ាអ៊ីសឃិន។ យើងនឹងប្រើផ្ទាំង `tf-models-official` ដើម្បីបង្កើតអុបទីម៉ាអ៊ីសឃិន៖


In [12]:
from official.nlp import optimization 
bert.trainable=True
model.summary()
epochs = 3
opt = optimization.create_optimizer(
    init_lr=3e-5,
    num_train_steps=epochs*len(ds_train),
    num_warmup_steps=0.1*epochs*len(ds_train),
    optimizer_type='adamw')

model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer=opt)
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           input_1[0][0]                    
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 4782465     keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

ដូចដែលអ្នកអាចឃើញ ការបណ្តុះបណ្តាលដំណើរការយ៉ាងយឺត - ប៉ុន្តែអ្នកអាចចង់សាកល្បង និងបណ្តុះបណ្តាលម៉ូដែលសម្រាប់រយៈពេលបណ្ដោះអាសន្នមួយចំនួន (5-10) ហើយមើលថាតើអ្នកអាចទទួលបានលទ្ធផលល្អបំផុតបើប្រៀបធៀបនឹងវិធីសាស្រ្តដែលយើងបានប្រើមុន។

## បណ្ណាល័យ Huggingface Transformers

វិធីសាស្រ្តមួយដែលពេញនិយមខ្លាំង (និងសាមញ្ញបន្តិច) ក្នុងការប្រើម៉ូដែល Transformer គឺ [HuggingFace package](https://github.com/huggingface/), ដែលផ្តល់ជាប្លុកសាងសម្រាប់ភារកិច្ច NLP ផ្សេងៗ។ វាមានសម្រាប់ទាំង Tensorflow និង PyTorch, មានគ្រាប់ខ្សែប្រព័ន្ធសរសៃប្រសាទមួយទៀតដែលពេញនិយម។

> **ចំណាំ**៖ ប្រសិនបើអ្នកមិនចាប់អារម្មណ៍ក្នុងការស្គាល់ថា បណ្ណាល័យ Transformers ធ្វើការយ៉ាងដូចម្តេចទេ - អ្នកអាចរំលងទៅចុងបញ្ចប់នៃសៀវភៅកំណត់ត្រានេះបាន ដោយសារ អ្នកនឹងមិនឃើញអ្វីខុសប្លែកយ៉ាងសំខាន់ពីអ្វីដែលយើងបានធ្វើខាងលើីទេស។ យើងនឹងធ្វើម្តងទៀតជំហានដូចគ្នានៃការបណ្តុះបណ្តាលម៉ូដែល BERT ដោយប្រើបណ្ណាល័យផ្សេង និងម៉ូដែលធំពេញមួយ។ ដូច្នេះ ដំណើរការនេះរួមបញ្ចូលការបណ្តុះបណ្តាលយូរមួយខ្លះ ដូច្នេះ អ្នកអាចចង់មើលតែមាតិកាកូដប៉ុណ្ណោះ។

មកមើលថា បញ្ហារបស់យើងអាចដោះស្រាយដោយប្រើ [Huggingface Transformers](http://huggingface.co) ដូចម្តេច។


រឿងដំបូងដែលយើងត្រូវធ្វើគឺជ្រើសរើសម៉ូដែលដែលយើងនឹងប្រើ។ បន្ថែមពីម៉ូដែលដែលបានកសាងមកដូចមានស្រាប់ហើយ Huggingface មាន [ឃ្លាំងម៉ូដែលអនឡាញ](https://huggingface.co/models) ដែលអ្នកអាចស្វែងរកម៉ូដែលបានបណ្តុះបណ្តាលជាច្រើនទៀតដោយសហគមន៍។ ម៉ូដែលទាំងអស់នោះអាចត្រូវបានបញ្ជូនចូល និងប្រើប្រាស់បានត្រឹមតែផ្ដល់ឈ្មោះម៉ូដែលប៉ុណ្ណោះ។ គ្រប់កំណត់ត្រាស៊ីស្ដមប៊ីណារបស់ម៉ូដែលនឹងត្រូវបានទាញយកដោយស្វ័យប្រវត្តិ។

ពេលខ្លះអ្នកនឹងត្រូវបញ្ជូនចូលម៉ូដែលរបស់អ្នកផ្ទាល់ ដោយក្នុងករណីនោះ អ្នកអាចបញ្ជាក់ថតដែលមានឯកសារសម្របសម្រួលទាំងអស់ រួមមានប៉ារ៉ាមែត្រ tokenizer, ឯកសារ `config.json` រួមបញ្ចូលប៉ារ៉ាមែត្រម៉ូដែល, ត្រូងទម្ងន់ប៊ីណាររួចដែរ។

ពីឈ្មោះម៉ូដែល អ្នកអាចបង្កើតម៉ូដែល និង tokenizer ទាំងពីរជាប្រភេទថ្នាក់មួយ។ យើងចាប់ផ្តើមជាមួយ tokenizer៖


In [2]:
import transformers

# To load the model from Internet repository using model name. 
# Use this if you are running from your own copy of the notebooks
bert_model = 'bert-base-uncased' 

# To load the model from the directory on disk. Use this for Microsoft Learn module, because we have
# prepared all required files for you.
#bert_model = './bert'

tokenizer = transformers.BertTokenizer.from_pretrained(bert_model)

MAX_SEQ_LEN = 128
PAD_INDEX = tokenizer.convert_tokens_to_ids(tokenizer.pad_token)
UNK_INDEX = tokenizer.convert_tokens_to_ids(tokenizer.unk_token)

អ объект `tokenizer` មានមុខងារ `encode` ដែលអាចប្រើប្រាស់ផ្ទាល់ក្នុងការត្រួតពិនិត្យអក្សរ ៖


In [3]:
tokenizer.encode('Tensorflow is a great framework for NLP')

[101, 23435, 12314, 2003, 1037, 2307, 7705, 2005, 17953, 2361, 102]

យើងក៏អាចប្រើ tokenizer ដើម្បីបញ្ចូលលេខសម្គាល់មួយជាលំដាប់ ដែលសមរម្យសម្រាប់ផ្ញើទៅម៉ូដែល។​ ឧទាហរណ៍ រួមមាន `token_ids`, វាល `input_mask` និងអ៊ីដូច្នេះទៀត។ យើងក៏អាចបញ្ជាក់ថាយើងចង់បាន Tensorflow tensors ដោយផ្តល់អាគុយម៉ង់ `return_tensors='tf'`:


In [4]:
tokenizer(['Hello, there'],return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101, 7592, 1010, 2045,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}

ក្នុងករណីរបស់យើង យើងនឹងប្រើម៉ូឌែល BERT ដែលបានបណ្តុះបណ្តាលរួចហើយដែលហៅថា `bert-base-uncased`។ *Uncased* បង្ហាញថាម៉ូឌែលនេះមិនអើពើអក្សរធំតូចឡើយ។

ពេលបណ្តុះបណ្តាលម៉ូឌែល យើងត្រូវផ្តល់លំដាប់ tokenized ជាឧបិន្ត និងដូច្នេះយើងនឹងរចនាដំណើរការបំបែកទិន្នន័យ។ ពីព្រោះ `tokenizer.encode` ជាអនុគមន៍ Python យើងនឹងប្រើវិធីសាស្ត្រដូចក្នុងផ្នែកចុងក្រោយ ដោយហៅវា​ដោយប្រើ `py_function`:


In [31]:
def process(x):
    return tokenizer.encode(x.numpy().decode('utf-8'),return_tensors='tf',padding='max_length',max_length=MAX_SEQ_LEN,truncation=True)[0]

def process_fn(x):
    s = x['title']+' '+x['description']
    e = tf.py_function(process,inp=[s],Tout=(tf.int32))
    e.set_shape(MAX_SEQ_LEN)
    return e,x['label']

ឥឡូវនេះយើងអាចផ្ទុកគំរូពិតប្រាកដដោយប្រើកញ្ចប់ `BertForSequenceClassfication`។ នេះធានាថាគំរូរបស់យើងមានរចនាសម្ព័ន្ធដែលត្រូវការសម្រាប់ចាត់ថ្នាក់រួចហើយ រួមទាំងម៉ាស៊ីនចាត់ថ្នាក់ចុងក្រោយ។ អ្នកនឹងឃើញសារ​រាស្រ្ត​ត្រូវ​បាន​បង្ហាញ​ថា ទំងន់​របស់​ម៉ាស៊ីន​ចាត់ថ្នាក់​ចុងក្រោយ​មិន​ត្រូវ​បាន​ចាប់ផ្ដើម ដែល​គំរូ​ត្រូវការបណ្តុះបណ្តាល​កម្រិត​ខាងមុខ - នេះល្អបំផុត ពីព្រោះ វាជាការដែលយើងកំពុងតែធ្វើ!


In [32]:
model = transformers.TFBertForSequenceClassification.from_pretrained(bert_model,num_labels=4,output_attentions=False)

In [33]:
model.summary()

Model: "tf_bert_for_sequence_classification_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  109482240 
_________________________________________________________________
dropout_75 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3076      
Total params: 109,485,316
Trainable params: 109,485,316
Non-trainable params: 0
_________________________________________________________________


ដូចដែល​អ្នក​អាច​ឃើញ​ពី​`summary()` គំរូ​មាន​ប៉ារ៉ាម៉ែត្រ​ប្រហែលជា ១១០លាន! ប្រហែល​ណាស់ ប្រសិនបើ​យើង​ចង់​ធ្វើ​បេសកកម្ម​ចាត់ថ្នាក់​សាមញ្ញ​លើ​កំណត់​ទិន្នន័យ​ខ្នាតតូច​ទៅមួយ យើង​មិន​ចង់​បណ្តុះ​ស្រទាប់មូលដ្ឋាន BERT ទេ៖


In [34]:
model.layers[0].trainable = False
model.summary()

Model: "tf_bert_for_sequence_classification_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  109482240 
_________________________________________________________________
dropout_75 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3076      
Total params: 109,485,316
Trainable params: 3,076
Non-trainable params: 109,482,240
_________________________________________________________________


ឥឡូវនេះយើងមានការត្រៀមខ្លួនធ្វើបណ្តុះបណ្តាលហើយ!

> **កំណត់ចំណាំ**៖ ការបណ្តុះបណ្តាលម៉ូដែល BERT ទំហំពេញអាចជាប់ពេលវេលាយូរ! ដូច្នេះយើងនឹងបណ្តុះបណ្តាលវាសម្រាប់ ៣២ បដិវេណ៍ដំបូងប៉ុណ្ណោះ។ នេះគ្រាន់តែបង្ហាញពីរបៀបដែលការបណ្តុះបណ្តាលម៉ូដែលត្រូវបានរៀបចំប៉ុណ្ណោះ។ ប្រសិនបើអ្នកចង់សាកល្បងបណ្តុះបណ្តាលទំហំពេញ - គ្រាន់តែដក parameter `steps_per_epoch` និង `validation_steps` ហើយត្រៀមខ្លួនរង់ចាំ!


In [30]:
model.compile('adam','sparse_categorical_crossentropy',['acc'])
tf.get_logger().setLevel('ERROR')
model.fit(ds_train.map(process_fn).batch(32),validation_data=ds_test.map(process_fn).batch(32),steps_per_epoch=32,validation_steps=2)

32/32 [==============================] - 142s 4s/step - loss: 1.3896 - acc: 0.2500 - val_loss: 1.3863 - val_acc: 0.2480


បើអ្នកបង្កើនចំនួន iteration ហើយរង់ចាំយូរពេញលេញ ហើយបណ្តុះសិក្សារយៈពេលជាច្រើន epoch អ្នកអាចរំពឹងថាការបែងចែកប្រភេទ BERT នឹងផ្តល់ជូននូវភាពត្រឹមត្រូវល្អបំផុត! នេះគឺដោយសារតែ BERT បានយល់ពីរចនាសម្ព័ន្ធភាសាយ៉ាងល្អហើយ ហើយយើងគ្រាន់តែត្រូវតែមិនធ្វើតែការត្រួតពិនិត្យ classifier ចុងក្រោយប៉ុណ្ណោះ។ ទោះជាយ៉ាងណាក៏ដោយ ព្រោះ BERT គឺជាគំរូធំ ដំណើរការបណ្តុះសិក្សាទាំងមូលចំណាយពេលប៉ុនប៉ងយូរ ហើយត្រូវការថាមពលគណនាប្រកបដោយភាពដាច់ខាត! (GPU និងល្អបំផុតមានល្មមជាងមួយ)។

> **កំណត់ចំណាំ:** ក្នុងឧទាហរណ៍របស់យើង យើងបានប្រើមួយក្នុងចំណោមគំរូ BERT ដែលតូចជាងគេដែលបានបណ្តុះបណ្តាលរួចមុន។ មានគំរូធំជាងនេះដែលមានសក្ដានុពលផ្តល់លទ្ធផលល្អជាង។


## Takeaway

នៅក្នុងឯកតានេះ យើងបានមើលឃើញរចនាសម្ព័ន្ធម៉ូដែលទំនើបៗថ្មីៗ ដែលផ្អែកលើ **transformers**។ យើងបានអនុវត្តវាសម្រាប់ការបែងចែកចំណាត់ថ្នាក់អក្សររបស់យើង ប៉ុន្តែដូចគ្នានេះ ម៉ូដែល BERT អាចប្រើសម្រាប់ការដកស្រង់អង្គភាព ការឆ្លើយសំណួរ និងភារកិច្ច NLP ផ្សេងទៀត។

ម៉ូដែល Transformer តំណាងឱ្យស្ថានភាព-of-the-art បច្ចុប្បន្ននៅក្នុង NLP ហើយក្នុងភាគច្រើននៃករណី វាគួរត្រូវបានជាជម្រើសដំបូងដែលអ្នកចាប់ផ្តើមសាកល្បងនៅពេលអនុវត្តដំណោះស្រាយ NLP ផ្ទាល់ខ្លួន។ ទោះជាយ៉ាងណា ការយល់ដឹងពីគ្រឹះមូលដ្ឋាននៃគោលការណ៍ផ្នែកបណ្តាញបញ្ជូនហ្វេនដែលបានពិភាក្សាក្នុងម៉ូឌុលនេះ គឺមានសារៈសំខាន់ខ្លាំង ប្រសិនបើអ្នកចង់កសាងម៉ូដែលណឺរ៉ូនកម្រិតខ្ពស់។


---

<!-- CO-OP TRANSLATOR DISCLAIMER START -->
**ការលើកឡើងកំហិត**៖  
ឯកសារនេះត្រូវបានបកប្រែដោយប្រើសេវាកម្មបកប្រែដោយ AI [Co-op Translator](https://github.com/Azure/co-op-translator)។ ខណៈពេលដែលយើងខិតខំព្យាយាមរកភាពច្បាស់លាស់ សូមជ្រាបថាការបកប្រែដោយស្វ័យប្រវត្តិអាចមានកំហុសឬមិនត្រឹមត្រូវ។ ឯកសារដើមដែលមានភាសាតំណើរបស់វាគួរត្រូវបានគេយកទៅជាអំពើគោលការណ៍។ សម្រាប់ព័ត៌មានសំខាន់ៗ ការបកប្រែដោយមនុស្សជំនាញគឺមានការណែនាំ។ យើងមិនទទួលខុសត្រូវចំពោះការយល់ច្រឡំនឹង ឬការបកប្រែខុសការពីការប្រើប្រាស់ការបកប្រែនេះឡើយ។
<!-- CO-OP TRANSLATOR DISCLAIMER END -->
