# ಗಮನ ಯಂತ್ರಗಳು ಮತ್ತು ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್‌ಗಳು

ಪುನರಾವರ್ತಿತ ಜಾಲಗಳ ಪ್ರಮುಖ ದೋಷವೆಂದರೆ ಸರಣಿಯಲ್ಲಿನ ಎಲ್ಲಾ ಪದಗಳು ಫಲಿತಾಂಶದ ಮೇಲೆ ಸಮಾನ ಪ್ರಭಾವ ಬೀರುತ್ತವೆ. ಇದರಿಂದ ನಾಮಿತ ಘಟಕ ಗುರುತಿಸುವಿಕೆ ಮತ್ತು ಯಂತ್ರ ಅನುವಾದದಂತಹ ಸರಣಿ-ನಿಂದ-ಸರಣಿ ಕಾರ್ಯಗಳಿಗೆ ಸಾಮಾನ್ಯ LSTM ಎನ್‌ಕೋಡರ್-ಡಿಕೋಡರ್ ಮಾದರಿಗಳೊಂದಿಗೆ ಅತೀಕೃಷ್ಟ ಕಾರ್ಯಕ್ಷಮತೆ ಉಂಟಾಗುತ್ತದೆ. ವಾಸ್ತವದಲ್ಲಿ, ಇನ್‌ಪುಟ್ ಸರಣಿಯ ನಿರ್ದಿಷ್ಟ ಪದಗಳು ಇತರ ಪದಗಳಿಗಿಂತ ಹೆಚ್ಚು ಪ್ರಭಾವ ಬೀರುತ್ತವೆ.

ಯಂತ್ರ ಅನುವಾದದಂತಹ ಸರಣಿ-ನಿಂದ-ಸರಣಿ ಮಾದರಿಯನ್ನು ಪರಿಗಣಿಸಿ. ಇದು ಎರಡು ಪುನರಾವರ್ತಿತ ಜಾಲಗಳ ಮೂಲಕ ಅನುಷ್ಠಾನಗೊಳ್ಳುತ್ತದೆ, ಇಲ್ಲಿ ಒಂದು ಜಾಲ (**ಎನ್‌ಕೋಡರ್**) ಇನ್‌ಪುಟ್ ಸರಣಿಯನ್ನು ಗುಪ್ತ ಸ್ಥಿತಿಗೆ ಸಂಕುಚಿತಗೊಳಿಸುತ್ತದೆ, ಮತ್ತು ಇನ್ನೊಂದು, **ಡಿಕೋಡರ್**, ಈ ಗುಪ್ತ ಸ್ಥಿತಿಯನ್ನು ಅನುವಾದಿತ ಫಲಿತಾಂಶವಾಗಿ ವಿಸ್ತರಿಸುತ್ತದೆ. ಈ ವಿಧಾನದಲ್ಲಿ ಸಮಸ್ಯೆ ಏನೆಂದರೆ ಜಾಲದ ಅಂತಿಮ ಸ್ಥಿತಿಗೆ ವಾಕ್ಯದ ಆರಂಭವನ್ನು ನೆನಪಿಡಲು ಕಷ್ಟವಾಗುತ್ತದೆ, ಇದರಿಂದ ದೀರ್ಘ ವಾಕ್ಯಗಳಲ್ಲಿ ಮಾದರಿಯ ಗುಣಮಟ್ಟ ಕೆಳಮಟ್ಟಕ್ಕೆ ಇಳಿಯುತ್ತದೆ.

**ಗಮನ ಯಂತ್ರಗಳು** RNNನ ಪ್ರತಿ ಔಟ್‌ಪುಟ್ ಭವಿಷ್ಯವಾಣಿ ಮೇಲೆ ಪ್ರತಿ ಇನ್‌ಪುಟ್ ವೆಕ್ಟರ್‌ನ ಸಾಂದರ್ಭಿಕ ಪ್ರಭಾವವನ್ನು ತೂಕ ನೀಡುವ ವಿಧಾನವನ್ನು ಒದಗಿಸುತ್ತವೆ. ಇದನ್ನು ಅನುಷ್ಠಾನಗೊಳಿಸುವ ವಿಧಾನವೆಂದರೆ ಇನ್‌ಪುಟ್ RNNನ ಮಧ್ಯಂತರ ಸ್ಥಿತಿಗಳ ಮತ್ತು ಔಟ್‌ಪುಟ್ RNNನ ನಡುವೆ ಶಾರ್ಟ್‌ಕಟ್‌ಗಳನ್ನು ಸೃಷ್ಟಿಸುವುದು. ಈ ರೀತಿಯಲ್ಲಿ, ಔಟ್‌ಪುಟ್ ಚಿಹ್ನೆ $y_t$ ರಚಿಸುವಾಗ, ನಾವು ಎಲ್ಲಾ ಇನ್‌ಪುಟ್ ಗುಪ್ತ ಸ್ಥಿತಿಗಳು $h_i$ಗಳನ್ನು ವಿಭಿನ್ನ ತೂಕ ಗುಣಾಂಕಗಳ $\alpha_{t,i}$ೊಂದಿಗೆ ಪರಿಗಣಿಸುತ್ತೇವೆ.

![ಚಿತ್ರವು ಎನ್‌ಕೋಡರ್/ಡಿಕೋಡರ್ ಮಾದರಿಯನ್ನು ಸೇರಿಸಿದ ಗಮನ ಪದರದೊಂದಿಗೆ ತೋರಿಸುತ್ತದೆ](../../../../../translated_images/kn/encoder-decoder-attention.7a726296894fb567.webp)
*ಎನ್‌ಕೋಡರ್-ಡಿಕೋಡರ್ ಮಾದರಿಯೊಂದಿಗೆ ಸೇರಿಸಿದ ಗಮನ ಯಂತ್ರವನ್ನು [Bahdanau et al., 2015](https://arxiv.org/pdf/1409.0473.pdf) ನಲ್ಲಿ ವಿವರಿಸಲಾಗಿದೆ, [ಈ ಬ್ಲಾಗ್ ಪೋಸ್ಟ್](https://lilianweng.github.io/lil-log/2018/06/24/attention-attention.html) ನಿಂದ ಉಲ್ಲೇಖಿಸಲಾಗಿದೆ*

ಗಮನ ಮ್ಯಾಟ್ರಿಕ್ಸ್ $\{\alpha_{i,j}\}$ ನಿರ್ದಿಷ್ಟ ಇನ್‌ಪುಟ್ ಪದಗಳು ಔಟ್‌ಪುಟ್ ಸರಣಿಯ ನಿರ್ದಿಷ್ಟ ಪದ ರಚನೆಯಲ್ಲಿ ಎಷ್ಟು ಪಾತ್ರ ವಹಿಸುತ್ತವೆ ಎಂಬುದನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತದೆ. ಕೆಳಗಿನ ಚಿತ್ರದಲ್ಲಿ ಇಂತಹ ಮ್ಯಾಟ್ರಿಕ್ಸ್ ಉದಾಹರಣೆ ನೀಡಲಾಗಿದೆ:

![ಚಿತ್ರವು RNNsearch-50 ಮೂಲಕ ಕಂಡುಬಂದ ಮಾದರಿ ಹೊಂದಾಣಿಕೆಯನ್ನು ತೋರಿಸುತ್ತದೆ, Bahdanau - arviz.org ನಿಂದ ತೆಗೆದುಕೊಂಡಿದೆ](../../../../../translated_images/kn/bahdanau-fig3.09ba2d37f202a6af.webp)

*ಚಿತ್ರ [Bahdanau et al., 2015](https://arxiv.org/pdf/1409.0473.pdf) (ಚಿತ್ರ 3) ನಿಂದ ತೆಗೆದುಕೊಂಡಿದೆ*

ಗಮನ ಯಂತ್ರಗಳು ನೈಸರ್ಗಿಕ ಭಾಷಾ ಪ್ರಕ್ರಿಯೆಯಲ್ಲಿ ಇತ್ತೀಚಿನ ಅಥವಾ ಸಮೀಪದ ಇತ್ತೀಚಿನ ಅತ್ಯುತ್ತಮ ಸ್ಥಿತಿಗೆ ಬಹುಮಟ್ಟಿಗೆ ಕಾರಣವಾಗಿವೆ. ಆದರೆ ಗಮನವನ್ನು ಸೇರಿಸುವುದರಿಂದ ಮಾದರಿ ಪರಿಮಾಣಗಳು ಬಹಳಷ್ಟು ಹೆಚ್ಚಾಗುತ್ತವೆ, ಇದರಿಂದ RNNಗಳೊಂದಿಗೆ ಪ್ರಮಾಣವರ್ಧನೆ ಸಮಸ್ಯೆಗಳು ಉಂಟಾಗಿವೆ. RNNಗಳನ್ನು ಪ್ರಮಾಣವರ್ಧಿಸಲು ಪ್ರಮುಖ ಅಡ್ಡಿ ಎಂದರೆ ಮಾದರಿಗಳ ಪುನರಾವರ್ತಿತ ಸ್ವಭಾವವು ತರಬೇತಿಯನ್ನು ಬ್ಯಾಚ್ ಮತ್ತು ಸಮಾಂತರಗೊಳಿಸುವುದನ್ನು ಕಷ್ಟಕರವಾಗಿಸುತ್ತದೆ. RNNನಲ್ಲಿ ಸರಣಿಯ ಪ್ರತಿ ಅಂಶವನ್ನು ಕ್ರಮಬದ್ಧವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳಿಸಬೇಕಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ಅದನ್ನು ಸುಲಭವಾಗಿ ಸಮಾಂತರಗೊಳಿಸಲಾಗುವುದಿಲ್ಲ.

ಈ ಅಡ್ಡಿಯೊಂದಿಗೆ ಗಮನ ಯಂತ್ರಗಳ ಅಳವಡಿಕೆಯಿಂದ ನಾವು ಇಂದು BERT ರಿಂದ OpenGPT3 ವರೆಗೆ ಬಳಸುವ ಅತ್ಯುತ್ತಮ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳನ್ನು ಸೃಷ್ಟಿಸಿದ್ದೇವೆ.

## ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳು

ಪ್ರತಿ ಹಿಂದಿನ ಭವಿಷ್ಯವಾಣಿಯ ಸಾಂದರ್ಭಿಕತೆಯನ್ನು ಮುಂದಿನ ಮೌಲ್ಯಮಾಪನ ಹಂತಕ್ಕೆ ಕಳುಹಿಸುವ ಬದಲು, **ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳು** **ಸ್ಥಾನಿಕ ಎನ್‌ಕೋಡಿಂಗ್‌ಗಳು** ಮತ್ತು **ಗಮನ** ಬಳಸಿ ನೀಡಲಾದ ಪಠ್ಯದ ವಿಂಡೋದಲ್ಲಿ ಇನ್‌ಪುಟ್‌ನ ಸಾಂದರ್ಭಿಕತೆಯನ್ನು ಹಿಡಿಯುತ್ತವೆ. ಕೆಳಗಿನ ಚಿತ್ರವು ಸ್ಥಳೀಯ ಎನ್‌ಕೋಡಿಂಗ್‌ಗಳು ಮತ್ತು ಗಮನವು ನೀಡಲಾದ ವಿಂಡೋದಲ್ಲಿ ಸಾಂದರ್ಭಿಕತೆಯನ್ನು ಹೇಗೆ ಹಿಡಿಯಬಹುದು ಎಂಬುದನ್ನು ತೋರಿಸುತ್ತದೆ.

![ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳಲ್ಲಿ ಮೌಲ್ಯಮಾಪನಗಳು ಹೇಗೆ ನಡೆಯುತ್ತವೆ ಎಂಬುದನ್ನು ತೋರಿಸುವ ಅನಿಮೇಟೆಡ್ GIF](../../../../../lessons/5-NLP/18-Transformers/images/transformer-animated-explanation.gif)

ಪ್ರತಿ ಇನ್‌ಪುಟ್ ಸ್ಥಾನವನ್ನು ಪ್ರತಿ ಔಟ್‌ಪುಟ್ ಸ್ಥಾನಕ್ಕೆ ಸ್ವತಂತ್ರವಾಗಿ ನಕ್ಷೆ ಮಾಡಲಾಗುವುದರಿಂದ, ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್‌ಗಳು RNNಗಳಿಗಿಂತ ಉತ್ತಮವಾಗಿ ಸಮಾಂತರಗೊಳಿಸಬಹುದು, ಇದರಿಂದ ಬಹಳ ದೊಡ್ಡ ಮತ್ತು ಹೆಚ್ಚು ಅಭಿವ್ಯಕ್ತ ಭಾಷಾ ಮಾದರಿಗಳನ್ನು ಸೃಷ್ಟಿಸಲು ಸಾಧ್ಯವಾಗುತ್ತದೆ. ಪ್ರತಿ ಗಮನ ತಲೆ ಪದಗಳ ನಡುವಿನ ವಿಭಿನ್ನ ಸಂಬಂಧಗಳನ್ನು ಕಲಿಯಲು ಬಳಸಬಹುದು, ಇದು ನಂತರದ ನೈಸರ್ಗಿಕ ಭಾಷಾ ಪ್ರಕ್ರಿಯೆ ಕಾರ್ಯಗಳನ್ನು ಸುಧಾರಿಸುತ್ತದೆ.

## ಸರಳ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿ ನಿರ್ಮಾಣ

Kerasನಲ್ಲಿ ನಿರ್ಮಿತ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಪದರವಿಲ್ಲ, ಆದರೆ ನಾವು ನಮ್ಮದೇ ಮಾದರಿಯನ್ನು ನಿರ್ಮಿಸಬಹುದು. ಹಿಂದಿನಂತೆ, ನಾವು AG News ಡೇಟಾಸೆಟ್‌ನ ಪಠ್ಯ ವರ್ಗೀಕರಣದ ಮೇಲೆ ಗಮನಹರಿಸುವೆವು, ಆದರೆ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳು ಹೆಚ್ಚು ಕಠಿಣ NLP ಕಾರ್ಯಗಳಲ್ಲಿ ಉತ್ತಮ ಫಲಿತಾಂಶ ತೋರಿಸುತ್ತವೆ ಎಂದು ಹೇಳುವುದು ಮುಖ್ಯ.


In [1]:
import tensorflow as tf
from tensorflow import keras
import tensorflow_datasets as tfds
import numpy as np

ds_train, ds_test = tfds.load('ag_news_subset').values()

def extract_text(x):
    return x['title']+' '+x['description']

def tupelize(x):
    return (extract_text(x),x['label'])

ಕೇರಾಸ್‌ನಲ್ಲಿ ಹೊಸ ಲೇಯರ್‌ಗಳು `Layer` ಕ್ಲಾಸ್ ಅನ್ನು subclass ಮಾಡಬೇಕು ಮತ್ತು `call` ಮೆಥಡ್ ಅನ್ನು ಅನುಷ್ಠಾನಗೊಳಿಸಬೇಕು. **ಸ್ಥಾನಿಕ ಎಂಬೆಡ್ಡಿಂಗ್** ಲೇಯರ್‌ನಿಂದ ಪ್ರಾರಂಭಿಸೋಣ. ನಾವು [ಕೇರಾಸ್ ಅಧಿಕೃತ ಡಾಕ್ಯುಮೆಂಟೇಶನ್‌ನಿಂದ ಕೆಲವು ಕೋಡ್](https://keras.io/examples/nlp/text_classification_with_transformer/) ಬಳಸಲಿದ್ದೇವೆ. ನಾವು ಎಲ್ಲಾ ಇನ್‌ಪುಟ್ ಸರಣಿಗಳನ್ನು `maxlen` ಉದ್ದಕ್ಕೆ ಪ್ಯಾಡ್ ಮಾಡಲಾಗಿದೆ ಎಂದು فرض ಮಾಡುತ್ತೇವೆ.


In [2]:
class TokenAndPositionEmbedding(keras.layers.Layer):
    def __init__(self, maxlen, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.token_emb = keras.layers.Embedding(input_dim=vocab_size, output_dim=embed_dim)
        self.pos_emb = keras.layers.Embedding(input_dim=maxlen, output_dim=embed_dim)
        self.maxlen = maxlen

    def call(self, x):
        maxlen = self.maxlen
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x+positions

ಈ ಲೇಯರ್ ಎರಡು `Embedding` ಲೇಯರ್‌ಗಳಿಂದ ಕೂಡಿದೆ: ಟೋಕನ್‌ಗಳನ್ನು ಎम्बೆಡ್ ಮಾಡಲು (ನಾವು ಹಿಂದಿನಂತೆ ಚರ್ಚಿಸಿದ ರೀತಿಯಲ್ಲಿ) ಮತ್ತು ಟೋಕನ್ ಸ್ಥಾನಗಳನ್ನು ಎम्बೆಡ್ ಮಾಡಲು. ಟೋಕನ್ ಸ್ಥಾನಗಳನ್ನು 0 ರಿಂದ `maxlen` ವರೆಗೆ ನೈಸರ್ಗಿಕ ಸಂಖ್ಯೆಗಳ ಸರಣಿಯಾಗಿ `tf.range` ಬಳಸಿ ರಚಿಸಲಾಗುತ್ತದೆ, ನಂತರ ಅದನ್ನು ಎम्बೆಡಿಂಗ್ ಲೇಯರ್ ಮೂಲಕ ಹಾದುಹೋಗುತ್ತದೆ. ಎರಡು ಫಲಿತಾಂಶ ಎम्बೆಡಿಂಗ್ ವೆಕ್ಟರ್‌ಗಳನ್ನು ಸೇರಿಸಲಾಗುತ್ತದೆ, ಇದರಿಂದ `maxlen`$\times$`embed_dim` ಆಕಾರದ ಸ್ಥಾನಾನುಕ್ರಮಿತ ಎम्बೆಡಿಂಗ್ ಪ್ರತಿನಿಧಾನ ಸೃಷ್ಟಿಯಾಗುತ್ತದೆ.

<img src="../../../../../translated_images/kn/pos-embedding.e41ce9b6cf6078af.webp" width="40%"/>

ಈಗ, ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಬ್ಲಾಕ್ ಅನ್ನು ಅನುಷ್ಠಾನಗೊಳಿಸೋಣ. ಇದು ಹಿಂದಿನದಾಗಿ ವ್ಯಾಖ್ಯಾನಿಸಿದ ಎम्बೆಡಿಂಗ್ ಲೇಯರ್‌ನ ಔಟ್‌ಪುಟ್ ಅನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ:


In [3]:
class TransformerBlock(keras.layers.Layer):
    def __init__(self, embed_dim, num_heads, ff_dim, rate=0.1):
        super(TransformerBlock, self).__init__()
        self.att = keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=embed_dim, name='attn')
        self.ffn = keras.Sequential(
            [keras.layers.Dense(ff_dim, activation="relu"), keras.layers.Dense(embed_dim),]
        )
        self.layernorm1 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.layernorm2 = keras.layers.LayerNormalization(epsilon=1e-6)
        self.dropout1 = keras.layers.Dropout(rate)
        self.dropout2 = keras.layers.Dropout(rate)

    def call(self, inputs, training):
        attn_output = self.att(inputs, inputs)
        attn_output = self.dropout1(attn_output, training=training)
        out1 = self.layernorm1(inputs + attn_output)
        ffn_output = self.ffn(out1)
        ffn_output = self.dropout2(ffn_output, training=training)
        return self.layernorm2(out1 + ffn_output)

Transformer ಸ್ಥಾನಾನುಕ್ರಮಿತ ಇನ್‌ಪುಟ್‌ಗೆ `MultiHeadAttention` ಅನ್ನು ಅನ್ವಯಿಸಿ, `maxlen`$\times$`embed_dim` ಆಯಾಮದ ಗಮನ ವೆಕ್ಟರ್ ಅನ್ನು ಉತ್ಪಾದಿಸುತ್ತದೆ, ಇದನ್ನು ನಂತರ ಇನ್‌ಪುಟ್ ಜೊತೆಗೆ ಮಿಶ್ರಣ ಮಾಡಿ `LayerNormalization` ಬಳಸಿ ಸಾಮಾನ್ಯೀಕರಿಸಲಾಗುತ್ತದೆ.

> **Note**: `LayerNormalization` ಅನ್ನು ಈ ಕಲಿಕೆ ಮಾರ್ಗದ *ಕಂಪ್ಯೂಟರ್ ವೀಷನ್* ಭಾಗದಲ್ಲಿ ಚರ್ಚಿಸಲಾದ `BatchNormalization` ಗೆ ಹೋಲಿಸಬಹುದು, ಆದರೆ ಇದು ಪ್ರತಿ ತರಬೇತಿ ಮಾದರಿಗಾಗಿ ಹಿಂದಿನ ಲೇಯರ್‌ನ ಔಟ್‌ಪುಟ್‌ಗಳನ್ನು ಸ್ವತಂತ್ರವಾಗಿ ಸಾಮಾನ್ಯೀಕರಿಸಿ ಅವುಗಳನ್ನು [-1..1] ಶ್ರೇಣಿಗೆ ತರುತ್ತದೆ.

ಈ ಲೇಯರ್‌ನ ಔಟ್‌ಪುಟ್ ನಂತರ `Dense` ನೆಟ್‌ವರ್ಕ್ (ನಮ್ಮ ಪ್ರಕರಣದಲ್ಲಿ - ಎರಡು ಲೇಯರ್ ಪರ್ಸೆಪ್ಟ್ರಾನ್) ಮೂಲಕ ಸಾಗಿಸಲಾಗುತ್ತದೆ, ಮತ್ತು ಫಲಿತಾಂಶವನ್ನು ಅಂತಿಮ ಔಟ್‌ಪುಟ್‌ಗೆ ಸೇರಿಸಲಾಗುತ್ತದೆ (ಅದು ಮತ್ತೆ ಸಾಮಾನ್ಯೀಕರಣಕ್ಕೆ ಒಳಗಾಗುತ್ತದೆ).

<img src="../../../../../translated_images/kn/transformer-layer.905e14747ca4e7d5.webp" width="30%" />

ಈಗ, ನಾವು ಸಂಪೂರ್ಣ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಯನ್ನು ವ್ಯಾಖ್ಯಾನಿಸಲು ಸಿದ್ಧರಾಗಿದ್ದೇವೆ:


In [4]:
embed_dim = 32  # Embedding size for each token
num_heads = 2  # Number of attention heads
ff_dim = 32  # Hidden layer size in feed forward network inside transformer
maxlen = 256
vocab_size = 20000

model = keras.models.Sequential([
    keras.layers.experimental.preprocessing.TextVectorization(max_tokens=vocab_size,output_sequence_length=maxlen, input_shape=(1,)),
    TokenAndPositionEmbedding(maxlen, vocab_size, embed_dim),
    TransformerBlock(embed_dim, num_heads, ff_dim),
    keras.layers.GlobalAveragePooling1D(),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(20, activation="relu"),
    keras.layers.Dropout(0.1),
    keras.layers.Dense(4, activation="softmax")
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
text_vectorization (TextVect (None, 256)               0         
_________________________________________________________________
token_and_position_embedding (None, 256, 32)           648192    
_________________________________________________________________
transformer_block (Transform (None, 256, 32)           10656     
_________________________________________________________________
global_average_pooling1d (Gl (None, 32)                0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 32)                0         
_________________________________________________________________
dense_2 (Dense)              (None, 20)                660       
_________________________________________________________________
dropout_3 (Dropout)          (None, 20)               

In [5]:
print('Training tokenizer')
model.layers[0].adapt(ds_train.map(extract_text))
model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer='adam')
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

Training tokenizer
938/938 [==============================] - 45s 39ms/step - loss: 0.4978 - acc: 0.8068 - val_loss: 0.2808 - val_acc: 0.9124


## BERT ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳು

**BERT** (Bidirectional Encoder Representations from Transformers) ಒಂದು ಬಹಳ ದೊಡ್ಡ ಬಹುಮಟ್ಟದ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ನೆಟ್‌ವರ್ಕ್ ಆಗಿದ್ದು, *BERT-base* ಗೆ 12 ಲೇಯರ್‌ಗಳು ಮತ್ತು *BERT-large* ಗೆ 24 ಲೇಯರ್‌ಗಳಿವೆ. ಈ ಮಾದರಿಯನ್ನು ಮೊದಲು ದೊಡ್ಡ ಪಠ್ಯ ಡೇಟಾ (ವಿಕಿಪೀಡಿಯಾ + ಪುಸ್ತಕಗಳು) ಮೇಲೆ ಅನ್‌ಸೂಪರ್ವೈಸ್‌ಡ್ ತರಬೇತಿಯಲ್ಲಿ (ವಾಕ್ಯದಲ್ಲಿ ಮಸ್ಕ್ ಮಾಡಲಾದ ಪದಗಳನ್ನು ಊಹಿಸುವ ಮೂಲಕ) ಪೂರ್ವ-ತರಬೇತಿ ಮಾಡಲಾಗುತ್ತದೆ. ಪೂರ್ವ-ತರಬೇತಿ ಸಮಯದಲ್ಲಿ, ಮಾದರಿ ಭಾಷೆಯ ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವ ಮಹತ್ವದ ಮಟ್ಟವನ್ನು ಅಳವಡಿಸಿಕೊಂಡು, ನಂತರ ಇತರ ಡೇಟಾಸೆಟ್‌ಗಳೊಂದಿಗೆ ಫೈನ್ ಟ್ಯೂನಿಂಗ್ ಮೂಲಕ ಉಪಯೋಗಿಸಬಹುದು. ಈ ಪ್ರಕ್ರಿಯೆಯನ್ನು **ಟ್ರಾನ್ಸ್‌ಫರ್ ಲರ್ನಿಂಗ್** ಎಂದು ಕರೆಯುತ್ತಾರೆ.

![picture from http://jalammar.github.io/illustrated-bert/](../../../../../translated_images/kn/jalammarBERT-language-modeling-masked-lm.34f113ea5fec4362.webp)

ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ವಾಸ್ತುಶಿಲ್ಪಗಳ ಹಲವು ಬದಲಾವಣೆಗಳಿವೆ, ಅವುಗಳಲ್ಲಿ BERT, DistilBERT, BigBird, OpenGPT3 ಮತ್ತು ಇನ್ನಷ್ಟು ಫೈನ್ ಟ್ಯೂನಿಂಗ್ ಮಾಡಬಹುದಾದವುಗಳಾಗಿವೆ.

ನಮ್ಮ ಪರಂಪರাগত ಕ್ರಮ ವರ್ಗೀಕರಣ ಸಮಸ್ಯೆಯನ್ನು ಪರಿಹರಿಸಲು ಪೂರ್ವ-ತರಬೇತಿಗೊಂಡ BERT ಮಾದರಿಯನ್ನು ಹೇಗೆ ಬಳಸಬಹುದು ಎಂದು ನೋಡೋಣ. ನಾವು [ಅಧಿಕೃತ ಡಾಕ್ಯುಮೆಂಟೇಶನ್](https://www.tensorflow.org/text/tutorials/classify_text_with_bert) ನಿಂದ ಆಲೋಚನೆ ಮತ್ತು ಕೆಲವು ಕೋಡ್ ಅನ್ನು ತೆಗೆದುಕೊಳ್ಳುತ್ತೇವೆ.

ಪೂರ್ವ-ತರಬೇತಿಗೊಂಡ ಮಾದರಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಲು, ನಾವು **Tensorflow hub** ಅನ್ನು ಬಳಸುತ್ತೇವೆ. ಮೊದಲು, BERT-ನಿರ್ದಿಷ್ಟ ವೆಕ್ಟರೈಜರ್ ಅನ್ನು ಲೋಡ್ ಮಾಡೋಣ:


In [1]:
import tensorflow_text 
import tensorflow_hub as hub
vectorizer = hub.KerasLayer('https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3')

ModuleNotFoundError: No module named 'tensorflow_text'

In [7]:
vectorizer(['I love transformers'])

{'input_type_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
       dtype=int32)>,
 'input_word_ids': <tf.Tensor: shape=(1, 128), dtype=int32, numpy=
 array([[  101,  1045,  2293, 19081,   102,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0, 

ಮೂಲ ನೆಟ್‌ವರ್ಕ್ ತರಬೇತಿ ಪಡೆದಿದ್ದ ಅದೇ ವೆಕ್ಟರೈಜರ್ ಅನ್ನು ಬಳಸುವುದು ಬಹುಮುಖ್ಯ. ಜೊತೆಗೆ, BERT ವೆಕ್ಟರೈಜರ್ ಮೂರು ಘಟಕಗಳನ್ನು ನೀಡುತ್ತದೆ:
* `input_word_ids`, ಇದು ಇನ್‌ಪುಟ್ ವಾಕ್ಯದ ಟೋಕನ್ ಸಂಖ್ಯೆಗಳ ಸರಣಿಯಾಗಿದೆ
* `input_mask`, ಇದು ಸರಣಿಯ ಯಾವ ಭಾಗವು ನಿಜವಾದ ಇನ್‌ಪುಟ್ ಅನ್ನು ಹೊಂದಿದೆ ಮತ್ತು ಯಾವುದು ಪ್ಯಾಡಿಂಗ್ ಆಗಿದೆ ಎಂದು ತೋರಿಸುತ್ತದೆ. ಇದು `Masking` ಲೇಯರ್ ನಿರ್ಮಿಸುವ ಮಾಸ್ಕ್‌ಗೆ ಸಮಾನವಾಗಿದೆ
* `input_type_ids` ಭಾಷಾ ಮಾದರೀಕರಣ ಕಾರ್ಯಗಳಿಗೆ ಬಳಸಲಾಗುತ್ತದೆ ಮತ್ತು ಒಂದು ಸರಣಿಯಲ್ಲಿ ಎರಡು ಇನ್‌ಪುಟ್ ವಾಕ್ಯಗಳನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಲು ಅನುಮತಿಸುತ್ತದೆ.

ಆಮೇಲೆ, ನಾವು BERT ವೈಶಿಷ್ಟ್ಯ ಎಕ್ಸ್ಟ್ರಾಕ್ಟರ್ ಅನ್ನು ಸ್ಥಾಪಿಸಬಹುದು:


In [8]:
bert = hub.KerasLayer('https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-4_H-128_A-2/1')

In [9]:
z = bert(vectorizer(['I love transformers']))
for i,x in z.items():
    print(f"{i} -> { len(x) if isinstance(x, list) else x.shape }")

pooled_output -> (1, 128)
encoder_outputs -> 4
sequence_output -> (1, 128, 128)
default -> (1, 128)


ಹೀಗಾಗಿ, BERT ಲೇಯರ್ ಹಲವಾರು ಉಪಯುಕ್ತ ಫಲಿತಾಂಶಗಳನ್ನು ನೀಡುತ್ತದೆ:
* `pooled_output` ಎಂದರೆ ಸರಣಿಯಲ್ಲಿನ ಎಲ್ಲಾ ಟೋಕನ್‌ಗಳ ಸರಾಸರಿ ಫಲಿತಾಂಶ. ಇದನ್ನು ಸಂಪೂರ್ಣ ನೆಟ್‌ವರ್ಕ್‌ನ ಬುದ್ಧಿವಂತ ಸಾಂದರ್ಭಿಕ ಎम्बೆಡ್ಡಿಂಗ್ ಎಂದು ನೋಡಬಹುದು. ಇದು ನಮ್ಮ ಹಿಂದಿನ ಮಾದರಿಯಲ್ಲಿ `GlobalAveragePooling1D` ಲೇಯರ್‌ನ ಔಟ್‌ಪುಟ್‌ಗೆ ಸಮಾನವಾಗಿದೆ.
* `sequence_output` ಎಂದರೆ ಕೊನೆಯ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಲೇಯರ್‌ನ ಔಟ್‌ಪುಟ್ (ನಮ್ಮ ಮೇಲಿನ ಮಾದರಿಯಲ್ಲಿ `TransformerBlock` ಔಟ್‌ಪುಟ್‌ಗೆ ಹೊಂದಿಕೆಯಾಗುತ್ತದೆ)
* `encoder_outputs` ಎಂದರೆ ಎಲ್ಲಾ ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಲೇಯರ್‌ಗಳ ಔಟ್‌ಪುಟ್‌ಗಳು. ನಾವು 4-ಲೇಯರ್ BERT ಮಾದರಿಯನ್ನು ಲೋಡ್ ಮಾಡಿದ್ದೇವೆ (ನೀವು ಹೆಸರುದಿಂದ ಅಂದಾಜಿಸಬಹುದು, ಇದರಲ್ಲಿ `4_H` ಇದೆ), ಅದರಲ್ಲಿ 4 ಟೆನ್ಸರ್‌ಗಳಿವೆ. ಕೊನೆಯದು `sequence_output` ಜೊತೆಗೆ ಒಂದೇ.

ಈಗ ನಾವು ಎಂಡ್-ಟು-ಎಂಡ್ ವರ್ಗೀಕರಣ ಮಾದರಿಯನ್ನು ವ್ಯಾಖ್ಯಾನಿಸುವೆವು. ನಾವು *ಫಂಕ್ಷನಲ್ ಮಾದರಿ ವ್ಯಾಖ್ಯಾನ* ಬಳಸುತ್ತೇವೆ, ಅಂದರೆ ನಾವು ಮಾದರಿ ಇನ್‌ಪುಟ್ ಅನ್ನು ವ್ಯಾಖ್ಯಾನಿಸಿ, ನಂತರ ಅದರ ಔಟ್‌ಪುಟ್ ಲೆಕ್ಕಿಸಲು ಸರಣಿಯ ಅಭಿವ್ಯಕ್ತಿಗಳನ್ನು ನೀಡುತ್ತೇವೆ. ನಾವು BERT ಮಾದರಿ ತೂಕಗಳನ್ನು ತರಬೇತಿಗೆ ಅಸಾಧ್ಯವಾಗಿಸುವೆವು ಮತ್ತು ಕೇವಲ ಅಂತಿಮ ವರ್ಗೀಕರಣಕಾರಿಯನ್ನು ತರಬೇತಿಗೆ ಒಳಪಡಿಸುವೆವು:


In [10]:
inp = keras.Input(shape=(),dtype=tf.string)
x = vectorizer(inp)
x = bert(x)
x = keras.layers.Dropout(0.1)(x['pooled_output'])
out = keras.layers.Dense(4,activation='softmax')(x)
model = keras.models.Model(inp,out)
bert.trainable = False
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           input_1[0][0]                    
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 4782465     keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

In [11]:
model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer='adam')
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

938/938 [==============================] - 528s 559ms/step - loss: 0.8056 - acc: 0.6983 - val_loss: 0.5953 - val_acc: 0.7888


ಶಿಕ್ಷಣಾರ್ಹ ಪರಿಮಾಣಗಳು ಕಡಿಮೆ ಇದ್ದರೂ, ಪ್ರಕ್ರಿಯೆ ನಿಧಾನವಾಗಿದೆ, ಏಕೆಂದರೆ BERT ವೈಶಿಷ್ಟ್ಯ ಸಂಗ್ರಾಹಕ ಗಣನಾತ್ಮಕವಾಗಿ ಭಾರವಾಗಿದೆ. ತರಬೇತಿ ಕೊರತೆ ಅಥವಾ ಮಾದರಿ ಪರಿಮಾಣಗಳ ಕೊರತೆಯಿಂದ ನಾವು ಸಮಂಜಸವಾದ ನಿಖರತೆಯನ್ನು ಸಾಧಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ ಎಂದು ತೋರುತ್ತದೆ.

BERT ತೂಕಗಳನ್ನು ಅನ್ಫ್ರೀಜ್ ಮಾಡಿ ಅದನ್ನು ಸಹ ತರಬೇತಿಮಾಡಿ ನೋಡೋಣ. ಇದಕ್ಕೆ ತುಂಬಾ ಕಡಿಮೆ ಕಲಿಕೆ ದರ ಬೇಕಾಗುತ್ತದೆ, ಮತ್ತು **warmup** ಬಳಸಿ ಹೆಚ್ಚು ಜಾಗರೂಕ ತರಬೇತಿ ತಂತ್ರವನ್ನು ಅನುಸರಿಸಬೇಕು, **AdamW** ಆಪ್ಟಿಮೈಜರ್ ಬಳಸಿ. ಆಪ್ಟಿಮೈಜರ್ ಸೃಷ್ಟಿಸಲು ನಾವು `tf-models-official` ಪ್ಯಾಕೇಜ್ ಬಳಸುತ್ತೇವೆ:


In [12]:
from official.nlp import optimization 
bert.trainable=True
model.summary()
epochs = 3
opt = optimization.create_optimizer(
    init_lr=3e-5,
    num_train_steps=epochs*len(ds_train),
    num_warmup_steps=0.1*epochs*len(ds_train),
    optimizer_type='adamw')

model.compile(loss='sparse_categorical_crossentropy',metrics=['acc'], optimizer=opt)
model.fit(ds_train.map(tupelize).batch(128),validation_data=ds_test.map(tupelize).batch(128))

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_type_ids': ( 0           input_1[0][0]                    
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 4782465     keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

ನೀವು ನೋಡಬಹುದು, ತರಬೇತಿ ಬಹಳ ನಿಧಾನವಾಗಿ ನಡೆಯುತ್ತಿದೆ - ಆದರೆ ನೀವು ಪ್ರಯೋಗ ಮಾಡಿ, ಕೆಲವು epochs (5-10) ತರಬೇತಿ ಮಾಡಿ, ನಾವು ಹಿಂದಿನ ವಿಧಾನಗಳೊಂದಿಗೆ ಹೋಲಿಸಿದಾಗ ಉತ್ತಮ ಫಲಿತಾಂಶವನ್ನು ಪಡೆಯಬಹುದೇ ಎಂದು ನೋಡಬಹುದು.

## Huggingface Transformers ಗ್ರಂಥಾಲಯ

ಮತ್ತೊಂದು ಬಹಳ ಸಾಮಾನ್ಯ (ಮತ್ತು ಸ್ವಲ್ಪ ಸರಳ) ವಿಧಾನ Transformer ಮಾದರಿಗಳನ್ನು ಬಳಸಲು [HuggingFace ಪ್ಯಾಕೇಜ್](https://github.com/huggingface/) ಆಗಿದ್ದು, ಇದು ವಿಭಿನ್ನ NLP ಕಾರ್ಯಗಳಿಗೆ ಸರಳ ನಿರ್ಮಾಣ ಘಟಕಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ. ಇದು Tensorflow ಮತ್ತು PyTorch ಎರಡಕ್ಕೂ ಲಭ್ಯವಿದೆ, ಮತ್ತೊಂದು ಬಹಳ ಜನಪ್ರಿಯ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್ ಫ್ರೇಮ್ವರ್ಕ್.

> **Note**: ನೀವು Transformers ಗ್ರಂಥಾಲಯ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ ಎಂದು ನೋಡಲು ಆಸಕ್ತಿ ಇಲ್ಲದಿದ್ದರೆ - ನೀವು ಈ ನೋಟ್ಬುಕ್‌ನ ಕೊನೆಯನ್ನು ತಲುಪಬಹುದು, ಏಕೆಂದರೆ ನಾವು ಮೇಲಿನಂತೆ ಮಾಡಿದ್ದರಿಂದ ಬಹುಮಟ್ಟಿಗೆ ವಿಭಿನ್ನವಾದ ಏನನ್ನೂ ನೀವು ನೋಡಲಾರಿರಿ. ನಾವು ಬೇರೆ ಗ್ರಂಥಾಲಯ ಮತ್ತು ಬಹುಮಟ್ಟಿಗೆ ದೊಡ್ಡ ಮಾದರಿಯನ್ನು ಬಳಸಿಕೊಂಡು BERT ಮಾದರಿಯನ್ನು ತರಬೇತಿಗೊಳಿಸುವ ಅದೇ ಹಂತಗಳನ್ನು ಪುನರಾವರ್ತಿಸುತ್ತೇವೆ. ಆದ್ದರಿಂದ, ಪ್ರಕ್ರಿಯೆ ಕೆಲವು ದೀರ್ಘ ತರಬೇತಿಯನ್ನು ಒಳಗೊಂಡಿದೆ, ಆದ್ದರಿಂದ ನೀವು ಕೇವಲ ಕೋಡ್ ಅನ್ನು ನೋಡಬಹುದು.

ನಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು [Huggingface Transformers](http://huggingface.co) ಬಳಸಿ ಹೇಗೆ ಪರಿಹರಿಸಬಹುದು ಎಂದು ನೋಡೋಣ.


ಮೊದಲನೆಯದಾಗಿ ನಾವು ಬಳಸಲಿರುವ ಮಾದರಿಯನ್ನು ಆಯ್ಕೆ ಮಾಡಬೇಕಾಗುತ್ತದೆ. ಕೆಲವು ಒಳಗೊಂಡಿರುವ ಮಾದರಿಗಳ ಜೊತೆಗೆ, Huggingface ನಲ್ಲಿ [ಆನ್ಲೈನ್ ಮಾದರಿ ಸಂಗ್ರಹಾಲಯ](https://huggingface.co/models) ಇದೆ, ಅಲ್ಲಿ ಸಮುದಾಯದಿಂದ ಪೂರ್ವ-ಪ್ರಶಿಕ್ಷಿತ ಅನೇಕ ಮಾದರಿಗಳನ್ನು ನೀವು ಕಂಡುಹಿಡಿಯಬಹುದು. ಆ ಎಲ್ಲಾ ಮಾದರಿಗಳನ್ನು ಕೇವಲ ಮಾದರಿ ಹೆಸರನ್ನು ನೀಡುವುದರಿಂದ ಲೋಡ್ ಮಾಡಿ ಬಳಸಬಹುದು. ಮಾದರಿಗಾಗಿ ಅಗತ್ಯವಿರುವ ಎಲ್ಲಾ ಬೈನರಿ ಫೈಲ್‌ಗಳು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಗುತ್ತವೆ.

ಕೆಲವು ಸಂದರ್ಭಗಳಲ್ಲಿ ನೀವು ನಿಮ್ಮ ಸ್ವಂತ ಮಾದರಿಗಳನ್ನು ಲೋಡ್ ಮಾಡಬೇಕಾಗಬಹುದು, ಆ ಸಂದರ್ಭದಲ್ಲಿ ಟೋಕನೈಜರ್‌ಗಾಗಿ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳು, ಮಾದರಿ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳೊಂದಿಗೆ `config.json` ಫೈಲ್, ಬೈನರಿ ತೂಕಗಳು ಮುಂತಾದ ಎಲ್ಲಾ ಸಂಬಂಧಿತ ಫೈಲ್‌ಗಳನ್ನು ಹೊಂದಿರುವ ಡೈರೆಕ್ಟರಿಯನ್ನು ನೀವು ಸೂಚಿಸಬಹುದು.

ಮಾದರಿ ಹೆಸರಿನಿಂದ, ನಾವು ಮಾದರಿಯ ಜೊತೆಗೆ ಟೋಕನೈಜರ್ ಅನ್ನು ಕೂಡ ಉದ್ಘಾಟಿಸಬಹುದು. ಟೋಕನೈಜರ್‌ನಿಂದ ಪ್ರಾರಂಭಿಸೋಣ:


In [2]:
import transformers

# To load the model from Internet repository using model name. 
# Use this if you are running from your own copy of the notebooks
bert_model = 'bert-base-uncased' 

# To load the model from the directory on disk. Use this for Microsoft Learn module, because we have
# prepared all required files for you.
#bert_model = './bert'

tokenizer = transformers.BertTokenizer.from_pretrained(bert_model)

MAX_SEQ_LEN = 128
PAD_INDEX = tokenizer.convert_tokens_to_ids(tokenizer.pad_token)
UNK_INDEX = tokenizer.convert_tokens_to_ids(tokenizer.unk_token)

`tokenizer` ವಸ್ತುವಿನಲ್ಲಿ ಪಠ್ಯವನ್ನು ನೇರವಾಗಿ ಎನ್‌ಕೋಡ್ ಮಾಡಲು ಬಳಸಬಹುದಾದ `encode` ಫಂಕ್ಷನ್ ಇದೆ:


In [3]:
tokenizer.encode('Tensorflow is a great framework for NLP')

[101, 23435, 12314, 2003, 1037, 2307, 7705, 2005, 17953, 2361, 102]

ನಾವು ಮಾದರಿಗೆ ಪಾಸ್ ಮಾಡಲು ಸೂಕ್ತವಾದ ರೀತಿಯಲ್ಲಿ ಸರಣಿಯನ್ನು ಎನ್‌ಕೋಡ್ ಮಾಡಲು ಟೋಕನೈಜರ್ ಅನ್ನು ಬಳಸಬಹುದು, ಅಂದರೆ `token_ids`, `input_mask` ಕ್ಷೇತ್ರಗಳನ್ನು ಸೇರಿಸುವುದು ಇತ್ಯಾದಿ. ನಾವು `return_tensors='tf'` ಆರ್ಗ್ಯುಮೆಂಟ್ ಅನ್ನು ನೀಡುವ ಮೂಲಕ ಟೆನ್ಸರ್‌ಫ್ಲೋ ಟೆನ್ಸರ್‌ಗಳನ್ನು ಬೇಕೆಂದು ಸೂಚಿಸಬಹುದು:


In [4]:
tokenizer(['Hello, there'],return_tensors='tf')

{'input_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 101, 7592, 1010, 2045,  102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[1, 1, 1, 1, 1]], dtype=int32)>}

ನಮ್ಮ ಪ್ರಕರಣದಲ್ಲಿ, ನಾವು `bert-base-uncased` ಎಂಬ ಪೂರ್ವ-ಪ್ರಶಿಕ್ಷಿತ BERT ಮಾದರಿಯನ್ನು ಬಳಸಲಿದ್ದೇವೆ. *Uncased* ಎಂದರೆ ಮಾದರಿ ಕೇಸ್-ಅಸಂವೇದನಶೀಲವಾಗಿದೆ.

ಮಾದರಿಯನ್ನು ತರಬೇತುಗೊಳಿಸುವಾಗ, ನಮಗೆ ಟೋಕನೈಜ್ ಮಾಡಿದ ಕ್ರಮವನ್ನು ಇನ್‌ಪುಟ್ ಆಗಿ ನೀಡಬೇಕಾಗುತ್ತದೆ, ಆದ್ದರಿಂದ ನಾವು ಡೇಟಾ ಪ್ರಕ್ರಿಯೆ ಪೈಪ್‌ಲೈನ್ ಅನ್ನು ವಿನ್ಯಾಸಗೊಳಿಸುವೆವು. `tokenizer.encode` ಒಂದು Python ಫಂಕ್ಷನ್ ಆಗಿರುವುದರಿಂದ, ನಾವು ಹಿಂದಿನ ಘಟಕದಲ್ಲಿ ಮಾಡಿದಂತೆ ಅದನ್ನು `py_function` ಬಳಸಿ ಕರೆಮಾಡುವ ವಿಧಾನವನ್ನು ಬಳಸುತ್ತೇವೆ:


In [31]:
def process(x):
    return tokenizer.encode(x.numpy().decode('utf-8'),return_tensors='tf',padding='max_length',max_length=MAX_SEQ_LEN,truncation=True)[0]

def process_fn(x):
    s = x['title']+' '+x['description']
    e = tf.py_function(process,inp=[s],Tout=(tf.int32))
    e.set_shape(MAX_SEQ_LEN)
    return e,x['label']

ಈಗ ನಾವು `BertForSequenceClassfication` ಪ್ಯಾಕೇಜ್ ಬಳಸಿ ನಿಜವಾದ ಮಾದರಿಯನ್ನು ಲೋಡ್ ಮಾಡಬಹುದು. ಇದು ನಮ್ಮ ಮಾದರಿಯಲ್ಲಿ ವರ್ಗೀಕರಣಕ್ಕಾಗಿ ಅಗತ್ಯವಿರುವ ವಾಸ್ತುಶಿಲ್ಪವನ್ನು, ಅಂತಿಮ ವರ್ಗೀಕರಣಕಾರಿಯನ್ನು ಸೇರಿಸಿ, ಹೊಂದಿರುವುದನ್ನು ಖಚಿತಪಡಿಸುತ್ತದೆ. ನೀವು ಅಂತಿಮ ವರ್ಗೀಕರಣಕಾರಿಯ ತೂಕಗಳು ಪ್ರಾರಂಭವಾಗಿಲ್ಲ ಎಂಬ ಎಚ್ಚರಿಕೆ ಸಂದೇಶವನ್ನು ಕಾಣುತ್ತೀರಿ, ಮತ್ತು ಮಾದರಿಗೆ ಪೂರ್ವ-ಪ್ರಶಿಕ್ಷಣ ಅಗತ್ಯವಿದೆ - ಅದು ಸಂಪೂರ್ಣವಾಗಿ ಸರಿಯಾಗಿದೆ, ಏಕೆಂದರೆ ನಾವು ಅದೇ ಮಾಡಬೇಕಾಗಿದೆ!


In [32]:
model = transformers.TFBertForSequenceClassification.from_pretrained(bert_model,num_labels=4,output_attentions=False)

In [33]:
model.summary()

Model: "tf_bert_for_sequence_classification_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  109482240 
_________________________________________________________________
dropout_75 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3076      
Total params: 109,485,316
Trainable params: 109,485,316
Non-trainable params: 0
_________________________________________________________________


ನೀವು `summary()` ನಿಂದ ನೋಡಬಹುದು, ಮಾದರಿಯಲ್ಲಿ ಸುಮಾರು 110 ಮಿಲಿಯನ್ ಪ್ಯಾರಾಮೀಟರ್‌ಗಳಿವೆ! ಸಾಮಾನ್ಯವಾಗಿ, ನಾವು ಸಣ್ಣ ಡೇಟಾಸೆಟ್‌ನಲ್ಲಿ ಸರಳ ವರ್ಗೀಕರಣ ಕಾರ್ಯವನ್ನು ಮಾಡಲು ಬಯಸಿದರೆ, ನಾವು BERT ಮೂಲ ಲೇಯರ್ ಅನ್ನು ತರಬೇತಿಗೆ ಒಳಪಡಿಸಲು ಬಯಸುವುದಿಲ್ಲ:


In [34]:
model.layers[0].trainable = False
model.summary()

Model: "tf_bert_for_sequence_classification_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
bert (TFBertMainLayer)       multiple                  109482240 
_________________________________________________________________
dropout_75 (Dropout)         multiple                  0         
_________________________________________________________________
classifier (Dense)           multiple                  3076      
Total params: 109,485,316
Trainable params: 3,076
Non-trainable params: 109,482,240
_________________________________________________________________


ಈಗ ನಾವು ತರಬೇತಿ ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಾಗಿದ್ದೇವೆ!

> **Note**: ಸಂಪೂರ್ಣ ಪ್ರಮಾಣದ BERT ಮಾದರಿಯನ್ನು ತರಬೇತಿಗೊಳಿಸುವುದು ಬಹಳ ಸಮಯ ತೆಗೆದುಕೊಳ್ಳಬಹುದು! ಆದ್ದರಿಂದ ನಾವು ಮೊದಲ 32 ಬ್ಯಾಚ್‌ಗಳಿಗಾಗಿ ಮಾತ್ರ ತರಬೇತಿಗೊಳಿಸುವೆವು. ಇದು ಮಾದರಿ ತರಬೇತಿ ಹೇಗೆ ಹೊಂದಿಸಲಾಗುತ್ತದೆ ಎಂಬುದನ್ನು ತೋರಿಸಲು ಮಾತ್ರ. ನೀವು ಸಂಪೂರ್ಣ ಪ್ರಮಾಣದ ತರಬೇತಿಯನ್ನು ಪ್ರಯತ್ನಿಸಲು ಆಸಕ್ತರಾಗಿದ್ದರೆ - `steps_per_epoch` ಮತ್ತು `validation_steps` ಪರಿಮಾಣಗಳನ್ನು ತೆಗೆದುಹಾಕಿ, ಮತ್ತು ಕಾಯಲು ಸಿದ್ಧರಾಗಿ!


In [30]:
model.compile('adam','sparse_categorical_crossentropy',['acc'])
tf.get_logger().setLevel('ERROR')
model.fit(ds_train.map(process_fn).batch(32),validation_data=ds_test.map(process_fn).batch(32),steps_per_epoch=32,validation_steps=2)

32/32 [==============================] - 142s 4s/step - loss: 1.3896 - acc: 0.2500 - val_loss: 1.3863 - val_acc: 0.2480


ನೀವು ಪುನರಾವೃತ್ತಿಗಳ ಸಂಖ್ಯೆಯನ್ನು ಹೆಚ್ಚಿಸಿ ಸಾಕಷ್ಟು ಸಮಯ ಕಾಯುತ್ತೀರಾ ಮತ್ತು ಹಲವಾರು ಎಪೋಕ್‌ಗಳಿಗಾಗಿ ತರಬೇತಿ ನೀಡುತ್ತೀರಾ, BERT ವರ್ಗೀಕರಣವು ಅತ್ಯುತ್ತಮ ನಿಖರತೆಯನ್ನು ನೀಡುತ್ತದೆ ಎಂದು ನಿರೀಕ್ಷಿಸಬಹುದು! ಇದಕ್ಕೆ ಕಾರಣ BERT ಈಗಾಗಲೇ ಭಾಷೆಯ ರಚನೆಯನ್ನು ಚೆನ್ನಾಗಿ ಅರ್ಥಮಾಡಿಕೊಂಡಿದೆ, ಮತ್ತು ನಾವು ಕೇವಲ ಅಂತಿಮ ವರ್ಗೀಕರಣೆಯನ್ನು ಸೂಕ್ಷ್ಮವಾಗಿ ಹೊಂದಿಸಬೇಕಾಗುತ್ತದೆ. ಆದಾಗ್ಯೂ, BERT ಒಂದು ದೊಡ್ಡ ಮಾದರಿಯಾಗಿರುವುದರಿಂದ, ಸಂಪೂರ್ಣ ತರಬೇತಿ ಪ್ರಕ್ರಿಯೆಗೆ ಹೆಚ್ಚು ಸಮಯ ಬೇಕಾಗುತ್ತದೆ ಮತ್ತು ಗಂಭೀರ ಗಣನ ಶಕ್ತಿಯನ್ನು ಅಗತ್ಯವಿರುತ್ತದೆ! (GPU, ಮತ್ತು ಆದ್ಯತೆಯಿಂದ ಒಂದುಕ್ಕಿಂತ ಹೆಚ್ಚು).

> **Note:** ನಮ್ಮ ಉದಾಹರಣೆಯಲ್ಲಿ, ನಾವು ಅತ್ಯಂತ ಸಣ್ಣ ಪೂರ್ವ-ತರಬೇತಿಗೊಂಡ BERT ಮಾದರಿಗಳಲ್ಲಿ ಒಂದನ್ನು ಬಳಸುತ್ತಿದ್ದೇವೆ. ಉತ್ತಮ ಫಲಿತಾಂಶಗಳನ್ನು ನೀಡುವ ಸಾಧ್ಯತೆ ಇರುವ ದೊಡ್ಡ ಮಾದರಿಗಳು ಇವೆ.


## ಸಾರಾಂಶ

ಈ ಘಟಕದಲ್ಲಿ, ನಾವು **ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್‌ಗಳು** ಆಧಾರಿತ ಅತ್ಯಾಧುನಿಕ ಮಾದರಿ ವಾಸ್ತುಶಿಲ್ಪಗಳನ್ನು ನೋಡಿದ್ದೇವೆ. ನಾವು ಅವುಗಳನ್ನು ನಮ್ಮ ಪಠ್ಯ ವರ್ಗೀಕರಣ ಕಾರ್ಯಕ್ಕೆ ಅನ್ವಯಿಸಿದ್ದೇವೆ, ಆದರೆ ಅದೇ ರೀತಿಯಲ್ಲಿ, BERT ಮಾದರಿಗಳನ್ನು ಘಟಕ ಹೊರತೆಗೆಯುವಿಕೆ, ಪ್ರಶ್ನೆ ಉತ್ತರಿಸುವಿಕೆ ಮತ್ತು ಇತರ NLP ಕಾರ್ಯಗಳಿಗೆ ಬಳಸಬಹುದು.

ಟ್ರಾನ್ಸ್‌ಫಾರ್ಮರ್ ಮಾದರಿಗಳು NLP ನಲ್ಲಿ ಪ್ರಸ್ತುತ ಅತ್ಯುತ್ತಮ ತಂತ್ರಜ್ಞಾನವನ್ನು ಪ್ರತಿನಿಧಿಸುತ್ತವೆ, ಮತ್ತು ಬಹುತೇಕ ಸಂದರ್ಭಗಳಲ್ಲಿ ಕಸ್ಟಮ್ NLP ಪರಿಹಾರಗಳನ್ನು ಅನುಷ್ಠಾನಗೊಳಿಸುವಾಗ ನೀವು ಮೊದಲನೆಯದಾಗಿ ಪ್ರಯೋಗಿಸಬೇಕಾದ ಪರಿಹಾರವಾಗಿರಬೇಕು. ಆದಾಗ್ಯೂ, ಈ ಘಟಕದಲ್ಲಿ ಚರ್ಚಿಸಲಾದ ಪುನರಾವರ್ತಿತ ನ್ಯೂರಲ್ ನೆಟ್‌ವರ್ಕ್‌ಗಳ ಮೂಲಭೂತ ತತ್ವಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವುದು ಅತ್ಯಂತ ಮುಖ್ಯ, ನೀವು ಉನ್ನತ ಮಟ್ಟದ ನ್ಯೂರಲ್ ಮಾದರಿಗಳನ್ನು ನಿರ್ಮಿಸಲು ಬಯಸಿದರೆ.


---

<!-- CO-OP TRANSLATOR DISCLAIMER START -->
**ಅಸ್ವೀಕರಣ**:  
ಈ ದಸ್ತಾವೇಜು [Co-op Translator](https://github.com/Azure/co-op-translator) ಎಂಬ AI ಅನುವಾದ ಸೇವೆಯನ್ನು ಬಳಸಿ ಅನುವಾದಿಸಲಾಗಿದೆ. ನಾವು ಶುದ್ಧತೆಯತ್ತ ಪ್ರಯತ್ನಿಸುತ್ತಿದ್ದರೂ, ಸ್ವಯಂಚಾಲಿತ ಅನುವಾದಗಳಲ್ಲಿ ತಪ್ಪುಗಳು ಅಥವಾ ಅಸತ್ಯತೆಗಳು ಇರಬಹುದು ಎಂದು ದಯವಿಟ್ಟು ಗಮನಿಸಿ. ಮೂಲ ಭಾಷೆಯಲ್ಲಿರುವ ಮೂಲ ದಸ್ತಾವೇಜನ್ನು ಅಧಿಕೃತ ಮೂಲವೆಂದು ಪರಿಗಣಿಸಬೇಕು. ಮಹತ್ವದ ಮಾಹಿತಿಗಾಗಿ, ವೃತ್ತಿಪರ ಮಾನವ ಅನುವಾದವನ್ನು ಶಿಫಾರಸು ಮಾಡಲಾಗುತ್ತದೆ. ಈ ಅನುವಾದ ಬಳಕೆಯಿಂದ ಉಂಟಾಗುವ ಯಾವುದೇ ತಪ್ಪು ಅರ್ಥಮಾಡಿಕೊಳ್ಳುವಿಕೆ ಅಥವಾ ತಪ್ಪು ವಿವರಣೆಗಳಿಗೆ ನಾವು ಹೊಣೆಗಾರರಾಗುವುದಿಲ್ಲ.
<!-- CO-OP TRANSLATOR DISCLAIMER END -->
